CREATE TABLE "Players" (
	"Id"	INTEGER NOT NULL,
	"Name"	INTEGER NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);

CREATE TABLE "Sports" (
	"Id"	INTEGER NOT NULL,
	"Name"	INTEGER NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);

CREATE TABLE "SportPositions" (
	"Id"	INTEGER NOT NULL,
	"SportId"	INTEGER,
	"Name"	TEXT NOT NULL,
	FOREIGN KEY (SportId) REFERENCES Sports(Id)
);

CREATE TABLE "Leagues" (
	"Id"	INTEGER NOT NULL,
	"SportId"	INTEGER,
	"Name"	TEXT NOT NULL,
	FOREIGN KEY (SportId) REFERENCES Sports(Id)
);

CREATE TABLE "Teams" (
	"Id"	INTEGER NOT NULL,
	"LeagueId"	INTEGER,
	"Name"	TEXT NOT NULL,
	FOREIGN KEY (LeagueId) REFERENCES Leagues(Id)
);

CREATE TABLE "TeamPlayers" (
	"Id"	INTEGER NOT NULL,
	"TeamId"	INTEGER,
	"PlayerId"	INTEGER,
	FOREIGN KEY ("TeamId") REFERENCES Teams(Id),
	FOREIGN KEY ("PlayerId") REFERENCES Players(Id)
);

CREATE TABLE DepthChartItems (
	"Id"	INTEGER NOT NULL,
	"TeamPlayerId"	INTEGER,
	"SportPositionId"	INTEGER,
	FOREIGN KEY ("TeamPlayerId") REFERENCES "TeamPlayers"(Id),
	FOREIGN KEY ("SportPositionId") REFERENCES "SportPositions"(Id)
);